[env:opta]
platform = ststm32
board = opta
framework = arduino

monitor_speed = 115200
upload_protocol = dfu
lib_ldf_mode = chain
lib_compat_mode = strict

; Sin dependencias externas:
; - Arduino.h y Serial forman parte de framework = arduino.
; - TankFillController.h es una librería local situada en include/.
