[env:esp32dev]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino

monitor_speed = 115200
lib_ldf_mode = chain
lib_compat_mode = strict

; Dependencia externa usada por src/main.cpp para la pantalla LCD 1602.
lib_deps =
    arduino-libraries/LiquidCrystal @ 1.0.7
